apiVersion: v1
kind: Service
metadata:
  labels:
    app: web-v3
  name: web-v3
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: web-v3
  sessionAffinity: None
  type: NodePort
